
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('PULLREQUESTCOPY_DATABASE_NAME') { 'pullrequestcopy_development' } %>
  username: <%= ENV.fetch('PULLREQUESTCOPY_DATABASE_USER') { '' } %>
  password: <%= ENV.fetch('PULLREQUESTCOPY_DATABAASE_PASSWORD') { '' } %>
  host: <%= ENV.fetch('PULLREQUESTCOPY_DATABASE_HOST') { 'localhost' }%>

test:
  <<: *default
  database: <%= ENV.fetch('PULLREQUESTCOPY_DATABASE_NAME') { 'pullrequest_test' } %>
  username: <%= ENV.fetch('PULLREQUESTCOPY_DATABASE_USER') { '' } %>
  password: <%= ENV.fetch('PULLREQUESTCOPY_DATABASE_PASSWORD') { '' } %>
  host: <%= ENV.fetch('PULLREQUESTCOPY_DATABASE_HOST') { 'localhost' } %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 20
